// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].jsx";
import * as $1 from "./routes/api/joke.js";
import * as $2 from "./routes/index.jsx";
import * as $3 from "./routes/joke.jsx";
import * as $$0 from "./islands/Counter.jsx";
import * as $$1 from "./islands/Joke.jsx";

const manifest = {
  routes: {
    "./routes/[name].jsx": $0,
    "./routes/api/joke.js": $1,
    "./routes/index.jsx": $2,
    "./routes/joke.jsx": $3,
  },
  islands: {
    "./islands/Counter.jsx": $$0,
    "./islands/Joke.jsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
